# config.toml
model = "llama3.2"

[gpus]
"harmony01.fhcrc.org:11432" = 0
"harmony01.fhcrc.org:11433" = 1
"harmony01.fhcrc.org:11434" = 2
"harmony01.fhcrc.org:11435" = 3
"harmony02.fhcrc.org:11432" = 0
"harmony02.fhcrc.org:11433" = 1
"harmony02.fhcrc.org:11434" = 2
"harmony02.fhcrc.org:11435" = 3
"harmony03.fhcrc.org:11432" = 0
"harmony03.fhcrc.org:11433" = 1
"harmony03.fhcrc.org:11434" = 2
"harmony03.fhcrc.org:11435" = 3
"harmony04.fhcrc.org:11432" = 0
"harmony04.fhcrc.org:11433" = 1
"harmony04.fhcrc.org:11434" = 2
"harmony04.fhcrc.org:11435" = 3
"harmony05.fhcrc.org:11432" = 0
"harmony05.fhcrc.org:11433" = 1
"harmony05.fhcrc.org:11434" = 2
"harmony05.fhcrc.org:11435" = 3
"harmony06.fhcrc.org:11432" = 0
"harmony06.fhcrc.org:11433" = 1
#"harmony06.fhcrc.org:11434" = 2
"harmony06.fhcrc.org:11435" = 3
"harmony07.fhcrc.org:11432" = 0
"harmony07.fhcrc.org:11433" = 1
"harmony07.fhcrc.org:11434" = 2
"harmony07.fhcrc.org:11435" = 3
