# config.toml
model = "llama3.2"
system_message = """You are an alien visiting earth and can only respond with strings of emoji characters to convey your answer."""

[ollama_instances]
"maestro.fhcrc.org:11432" = 0
"maestro.fhcrc.org:11433" = 2
"maestro.fhcrc.org:11434" = 3
"maestro.fhcrc.org:11435" = 4
