[project]
name = "ollama-batch-cluster"
version = "0.1.0"
description = "Ollama Batch Cluster"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.3.3",
    "toml>=0.10.2",
]
